#Application-specific settings; usually left as generated by Django.
from django.apps import AppConfig

class MainAppConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'main'
    verbose_name = 'Macroinvertebrate Index Calculator'  # Human-readable name for the app

